name: "[master] Release"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - ".vscode/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Build:
    uses: ./.github/workflows/build.yml

  Release:
    name: Release latest on GitHub
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: luna-artifacts
          path: ./dist/

      - name: Publish latest release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          files: ./dist/**
